---

name: Push Helm Chart to ChartMuseum
on: 
  workflow_call: 
    inputs:
      CM_PUSH_HELM_VERSION:
        description: 'Defines the version of Helm to install, e.g. v3.11.3'
        required: true 
        type: string
    secrets:
      CM_BASICAUTH_USERNAME: 
        description: 'ChartMuseum Basic HTTP Authentication Username'
        required: true 
      CM_BASICAUTH_PASSWORD:
        description: 'ChartMuseum Basic HTTP Authentication Username'
        required: true
  
jobs:
  push_helm_chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repo 
        uses: actions/checkout@v3

      - name: Install Helm 
        uses: azure/setup-helm@v3
        with:
          version: ${{ inputs.CM_PUSH_HELM_VERSION }}

      - name: Install Helm ChartMuseum plugin
        run: |
          helm plugin install https://github.com/chartmuseum/helm-push
      
      - name: Add ChartMuseum repo 
        run: |
          helm repo add uclalibcm https://chartmuseum.library.ucla.edu
      
      - name: Push Helm Chart to ChartMuseum repo
        env: 
          HELM_REPO_USERNAME: ${{ secrets.CM_BASICAUTH_USERNAME }}
          HELM_REPO_PASSWORD: ${{ secrets.CM_BASICAUTH_PASSWORD }}
        run: |
          helm cm-push charts/ uclalibcm